import { useContext } from "react";
import { ThemeContext } from "../../components/ThemeContext";

import Head from "next/head";
import Navbar from "../../components/Navbar";
import CartSummary from "../../components/CartSummary";
import FormBox from "../../components/FormBox";

import styles from "@/styles/checkout.module.scss";

export default function Home() {
  const { theme } = useContext(ThemeContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={ theme }>
        <div className='background wrapper'>
          <Navbar />
          <div className={ styles['wrapper'] }>
            <CartSummary />
            <FormBox />
          </div>
        </div>
      </div>
    </>
  )
}
